### ISSUE TITLE
Learn how to write a basic Node.js file and run it

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/beginning-nodejs#1]
**Scenario** 

Write a very basic mathematical library with handy mathematical functions

**Tasks**

- [x] inside _activity-a_  folder create a file using `touch math.js` command, 
- [x] inside the math.js file, create the following functions: 
        - add: takes 2 arguments and return the sum of both. Example add(2, 5) returns 7
        - sum: takes any number of numeric arguments and return their sum. Example sum(10, 5, 6) returns 21
- [x] after writing the 2 functions, write code to display their returned value as a test 
- [x] run the code

**Comment by OpenTechConsult** [comment]
Done
